#!/bin/bash

echo -e "\e[1;32mDepending's are installing ..... \e[0m"
echo -e""
yum install -y python > /dev/null 2>&1
yum install wget > /dev/null 2>&1
wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py > /dev/null 2>&1
chmod +x speedtest-cli
echo -e "\e[1;32mDepending's are installed ..... \e[0m"
