#!/bin/bash

#Terminal Clear
reset

# Welcome Note
echo -e "\e[1;33m---------------------------------------------------------"
echo -e "JEEBANHOST SMT (Version 1.0)"
echo -e "All in one server management tool"
echo -e "For CentOS Operating System & cPanel / WHM Control Panel"
echo -e "Our Website: JEEBANHOST.IN"
echo -e "---------------------------------------------------------\e[0m"
echo -e""
rm -rf dependings
curl -L -o "dependings" "raw.githubusercontent.com/itsmejeeban/smt/main/dependings"
chmod +x dependings
./dependings


