#!/bin/bash

#Terminal Clear
reset

# Welcome Note
echo -e "\e[1;33m---------------------------------------------------------"
echo -e "JEEBANHOST SMT (Version 1.0)"
echo -e "All in one server management tool"
echo -e "For CentOS Operating System & cPanel / WHM Control Panel"
echo -e "Our Website: JEEBANHOST.IN"
echo -e "---------------------------------------------------------\e[0m"
echo -e""
echo -e "\e[1;32mDependings are installing ..... \e[0m"
echo -e""
yum install -y python > /dev/null 2>&1
yum install wget > /dev/null 2>&1
wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py > /dev/null 2>&1
chmod +x speedtest-cli
echo -e "\e[1;32mDepending Installed ..... \e[0m"
